# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 381)
        MainWindow.setMinimumSize(QtCore.QSize(420, 381))
        MainWindow.setMaximumSize(QtCore.QSize(420, 381))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/calculatoricon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"\n"
"background-color: rgb(94, 92, 100);")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(20, 130, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_7.setFont(font)
        self.btn_7.setAutoFillBackground(False)
        self.btn_7.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(100, 130, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_8.setFont(font)
        self.btn_8.setAutoFillBackground(False)
        self.btn_8.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(180, 130, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_9.setFont(font)
        self.btn_9.setAutoFillBackground(False)
        self.btn_9.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_9.setObjectName("btn_9")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(20, 190, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_4.setFont(font)
        self.btn_4.setAutoFillBackground(False)
        self.btn_4.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(100, 190, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_5.setFont(font)
        self.btn_5.setAutoFillBackground(False)
        self.btn_5.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(180, 190, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_6.setFont(font)
        self.btn_6.setAutoFillBackground(False)
        self.btn_6.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_6.setObjectName("btn_6")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(20, 250, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_1.setFont(font)
        self.btn_1.setAutoFillBackground(False)
        self.btn_1.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(100, 250, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2.setFont(font)
        self.btn_2.setAutoFillBackground(False)
        self.btn_2.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(180, 250, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_3.setFont(font)
        self.btn_3.setAutoFillBackground(False)
        self.btn_3.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_3.setObjectName("btn_3")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(20, 310, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_0.setFont(font)
        self.btn_0.setAutoFillBackground(False)
        self.btn_0.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_0.setObjectName("btn_0")
        self.btn_00 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_00.setGeometry(QtCore.QRect(100, 310, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_00.setFont(font)
        self.btn_00.setAutoFillBackground(False)
        self.btn_00.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_00.setObjectName("btn_00")
        self.btn_dot = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dot.setGeometry(QtCore.QRect(180, 310, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dot.setFont(font)
        self.btn_dot.setAutoFillBackground(False)
        self.btn_dot.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_dot.setObjectName("btn_dot")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(260, 250, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_minus.setFont(font)
        self.btn_minus.setAutoFillBackground(False)
        self.btn_minus.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(260, 190, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_plus.setFont(font)
        self.btn_plus.setAutoFillBackground(False)
        self.btn_plus.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_slash = QtWidgets.QPushButton(self.centralwidget)
        self.btn_slash.setGeometry(QtCore.QRect(260, 310, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_slash.setFont(font)
        self.btn_slash.setAutoFillBackground(False)
        self.btn_slash.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_slash.setObjectName("btn_slash")
        self.btn_bkspace = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bkspace.setGeometry(QtCore.QRect(260, 130, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_bkspace.setFont(font)
        self.btn_bkspace.setAutoFillBackground(False)
        self.btn_bkspace.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_bkspace.setObjectName("btn_bkspace")
        self.btn_present = QtWidgets.QPushButton(self.centralwidget)
        self.btn_present.setGeometry(QtCore.QRect(340, 250, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_present.setFont(font)
        self.btn_present.setAutoFillBackground(False)
        self.btn_present.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_present.setObjectName("btn_present")
        self.btn_c = QtWidgets.QPushButton(self.centralwidget)
        self.btn_c.setGeometry(QtCore.QRect(340, 130, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_c.setFont(font)
        self.btn_c.setAutoFillBackground(False)
        self.btn_c.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_c.setObjectName("btn_c")
        self.btn_25 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_25.setGeometry(QtCore.QRect(340, 190, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_25.setFont(font)
        self.btn_25.setAutoFillBackground(False)
        self.btn_25.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_25.setObjectName("btn_25")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(340, 310, 71, 51))
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_equal.setFont(font)
        self.btn_equal.setAutoFillBackground(False)
        self.btn_equal.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"alternate-background-color: rgb(119, 118, 123);\n"
"")
        self.btn_equal.setObjectName("btn_equal")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn_0.clicked.connect(lambda :self.calc_funcation('0'))
        self.btn_00.clicked.connect(lambda :self.calc_funcation('00'))
        self.btn_1.clicked.connect(lambda :self.calc_funcation('1'))
        self.btn_2.clicked.connect(lambda :self.calc_funcation('2'))
        self.btn_3.clicked.connect(lambda :self.calc_funcation('3'))
        self.btn_4.clicked.connect(lambda :self.calc_funcation('4'))
        self.btn_5.clicked.connect(lambda :self.calc_funcation('5'))
        self.btn_6.clicked.connect(lambda :self.calc_funcation('6'))
        self.btn_7.clicked.connect(lambda :self.calc_funcation('7'))
        self.btn_8.clicked.connect(lambda :self.calc_funcation('8'))
        self.btn_9.clicked.connect(lambda :self.calc_funcation('9'))
        self.btn_dot.clicked.connect(lambda :self.calc_funcation('.'))
        self.btn_slash.clicked.connect(lambda :self.calc_funcation('/'))
        self.btn_minus.clicked.connect(lambda :self.calc_funcation('-'))
        self.btn_plus.clicked.connect(lambda :self.calc_funcation('+'))
        self.btn_present.clicked.connect(lambda :self.calc_funcation('%'))
        self.btn_25.clicked.connect(lambda :self.calc_funcation('*'))
        self.btn_c.clicked.connect(self.clear)
        self.btn_bkspace.clicked.connect(self.bk_space)
        self.btn_equal.clicked.connect(self.equal)

    def bk_space(self):
        text = self.label.text()
        self.label.setText(text[:len(text)-1])

    def clear(self):
        self.label.setText("")

    def calc_funcation(self, button):
        text = self.label.text()
        self.label.setText(text+button)
    def equal(self):
        text = self.label.text()
        try:
           ans =eval(text)
           self.label.setText(str(ans))
        except:
              self.label.setText("wrong")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "calculator"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_00.setText(_translate("MainWindow", "00"))
        self.btn_dot.setText(_translate("MainWindow", "."))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_slash.setText(_translate("MainWindow", "/"))
        self.btn_bkspace.setText(_translate("MainWindow", "<"))
        self.btn_present.setText(_translate("MainWindow", "%"))
        self.btn_c.setText(_translate("MainWindow", "c"))
        self.btn_25.setText(_translate("MainWindow", "x"))
        self.btn_equal.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
